version: '3.6'

services:
  vpn:
    build: .
    image: netlykos/ipsec-vpn-server
    restart: always
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
    hostname: ipsec-vpn-server
    container_name: ipsec-vpn-server
    cap_add:
      - NET_ADMIN
    labels:
      org.netlykos.description: "ipsec-vpn-server"
      org.netlykos.label: "ipsec-vpn-server"
